// test_itch.cpp — ITCH codec vs the committed golden vectors
// (cpp/test/vectors/itch.json, generated by the proven Python prototype),
// plus negative decode tests.
#include "itch/itch.h"

#include <cstring>
#include <string>
#include <vector>

#include "common/minitest.h"
#include "test/jsonvec.h"

namespace {

// Named field access on the flat ItchMsg so vector comparison is generic.
bool get_int_field(const jnx::ItchMsg& m, const std::string& name,
                   uint64_t& out) {
    if (name == "seconds") out = m.seconds;
    else if (name == "ns") out = m.ns;
    else if (name == "tick_table_id") out = m.tick_table_id;
    else if (name == "tick_size") out = m.tick_size;
    else if (name == "price_start") out = m.price_start;
    else if (name == "round_lot") out = m.round_lot;
    else if (name == "price_decimals") out = m.price_decimals;
    else if (name == "upper_limit") out = m.upper_limit;
    else if (name == "lower_limit") out = m.lower_limit;
    else if (name == "order_number") out = m.order_number;
    else if (name == "qty") out = m.qty;
    else if (name == "price") out = m.price;
    else if (name == "executed_qty") out = m.executed_qty;
    else if (name == "match_number") out = m.match_number;
    else if (name == "orig_order_number") out = m.orig_order_number;
    else if (name == "new_order_number") out = m.new_order_number;
    else if (name == "sequence_number") out = m.sequence_number;
    else return false;
    return true;
}

// Single-char alpha as stripped string: a space (blank field on the wire)
// compares as "" — mirroring the prototype's alpha-stripping in vectors.
std::string char_field(char c) {
    return c == ' ' ? std::string() : std::string(1, c);
}

bool get_str_field(const jnx::ItchMsg& m, const std::string& name,
                   std::string& out) {
    if (name == "group") out = m.group;
    else if (name == "orderbook_id") out = m.orderbook_id;
    else if (name == "isin") out = m.isin;
    else if (name == "attribution") out = m.attribution;
    else if (name == "event") out = char_field(m.event);
    else if (name == "state") out = char_field(m.state);
    else if (name == "side") out = char_field(m.side);
    else if (name == "order_type") out = char_field(m.order_type);
    else return false;
    return true;
}

std::string vectors_path() {
    // `make -C cpp test` runs binaries with cwd = cpp/; also tolerate
    // running from the repo root by hand.
    std::ifstream probe("test/vectors/itch.json");
    if (probe.is_open()) {
        return "test/vectors/itch.json";
    }
    return "cpp/test/vectors/itch.json";
}

} // namespace

TEST(itch_golden_vectors_decode_and_reencode) {
    std::vector<jsonvec::Vector> vecs;
    CHECK(jsonvec::load(vectors_path(), vecs));
    CHECK_EQ(vecs.size(), static_cast<size_t>(37));
    for (size_t i = 0; i < vecs.size(); ++i) {
        const jsonvec::Vector& v = vecs[i];
        std::vector<unsigned char> bytes;
        CHECK(jsonvec::hex_to_bytes(v.hex, bytes));

        jnx::ItchMsg msg;
        const char* err = NULL;
        bool ok = jnx::decode(&bytes[0], bytes.size(), msg, &err);
        if (!ok) {
            std::fprintf(stderr, "  vector %s: decode failed: %s\n",
                         v.name.c_str(), err ? err : "?");
            CHECK(ok);
            continue;
        }
        CHECK_EQ(std::string(1, msg.type), v.type);

        // Every int field in the vector must match the decoded struct.
        for (std::map<std::string, uint64_t>::const_iterator it =
                 v.int_fields.begin();
             it != v.int_fields.end(); ++it) {
            uint64_t got = 0;
            bool known = get_int_field(msg, it->first, got);
            if (!known) {
                std::fprintf(stderr, "  vector %s: unknown int field %s\n",
                             v.name.c_str(), it->first.c_str());
            }
            CHECK(known);
            if (known && got != it->second) {
                std::fprintf(stderr, "  vector %s field %s\n", v.name.c_str(),
                             it->first.c_str());
                CHECK_EQ(got, it->second);
            }
        }
        // Every string field likewise.
        for (std::map<std::string, std::string>::const_iterator it =
                 v.str_fields.begin();
             it != v.str_fields.end(); ++it) {
            std::string got;
            bool known = get_str_field(msg, it->first, got);
            if (!known) {
                std::fprintf(stderr, "  vector %s: unknown str field %s\n",
                             v.name.c_str(), it->first.c_str());
            }
            CHECK(known);
            if (known && got != it->second) {
                std::fprintf(stderr, "  vector %s field %s\n", v.name.c_str(),
                             it->first.c_str());
                CHECK_EQ(got, it->second);
            }
        }

        // Re-encode must be byte-identical to the golden bytes.
        unsigned char out[64];
        size_t n = jnx::encode(msg, out);
        CHECK_EQ(n, bytes.size());
        if (n == bytes.size()) {
            bool same = true;
            for (size_t j = 0; j < n; ++j) {
                if (out[j] != bytes[j]) same = false;
            }
            if (!same) {
                std::fprintf(stderr, "  vector %s: re-encode differs\n",
                             v.name.c_str());
            }
            CHECK(same);
        }
    }
}

TEST(itch_expected_len_table) {
    CHECK_EQ(jnx::expected_len('T'), 5);
    CHECK_EQ(jnx::expected_len('S'), 10);
    CHECK_EQ(jnx::expected_len('L'), 17);
    CHECK_EQ(jnx::expected_len('R'), 45);
    CHECK_EQ(jnx::expected_len('H'), 14);
    CHECK_EQ(jnx::expected_len('Y'), 14);
    CHECK_EQ(jnx::expected_len('A'), 30);
    CHECK_EQ(jnx::expected_len('F'), 35);
    CHECK_EQ(jnx::expected_len('E'), 25);
    CHECK_EQ(jnx::expected_len('D'), 13);
    CHECK_EQ(jnx::expected_len('U'), 29);
    CHECK_EQ(jnx::expected_len('G'), 9);
    CHECK_EQ(jnx::expected_len('X'), -1);
    CHECK_EQ(jnx::expected_len('\0'), -1);
}

TEST(itch_truncated_buffers_rejected) {
    // Build valid A and E messages, then try every truncated length.
    jnx::ItchMsg a;
    a.type = 'A';
    a.ns = 1;
    a.order_number = 42;
    a.side = 'B';
    a.qty = 100;
    std::snprintf(a.orderbook_id, sizeof(a.orderbook_id), "8306");
    std::snprintf(a.group, sizeof(a.group), "DAY");
    a.price = 15000;
    unsigned char abuf[64];
    size_t alen = jnx::encode(a, abuf);
    CHECK_EQ(alen, static_cast<size_t>(30));
    for (size_t len = 0; len < alen; ++len) {
        jnx::ItchMsg out;
        const char* err = NULL;
        CHECK(!jnx::decode(abuf, len, out, &err));
        CHECK(err != NULL);
    }

    jnx::ItchMsg e;
    e.type = 'E';
    e.ns = 2;
    e.order_number = 42;
    e.executed_qty = 10;
    e.match_number = 7;
    unsigned char ebuf[64];
    size_t elen = jnx::encode(e, ebuf);
    CHECK_EQ(elen, static_cast<size_t>(25));
    for (size_t len = 0; len < elen; ++len) {
        jnx::ItchMsg out;
        const char* err = NULL;
        CHECK(!jnx::decode(ebuf, len, out, &err));
        CHECK(err != NULL);
    }

    // Over-long buffers must be rejected too (strict length).
    jnx::ItchMsg out;
    const char* err = NULL;
    CHECK(!jnx::decode(abuf, alen + 1, out, &err));
}

TEST(itch_unknown_type_rejected) {
    unsigned char buf[16];
    std::memset(buf, 0, sizeof(buf));
    buf[0] = 'X';
    jnx::ItchMsg out;
    const char* err = NULL;
    CHECK(!jnx::decode(buf, 5, out, &err));
    CHECK(err != NULL);
}

TEST(itch_no_price_roundtrip_untouched) {
    // Reference-price A with the NO_PRICE sentinel must decode as a plain
    // A (order_number 0 carries no special casing at codec level) and the
    // sentinel must survive encode/decode bit-exact.
    jnx::ItchMsg a;
    a.type = 'A';
    a.ns = 123;
    a.order_number = 0; // ref-price carrier — still a normal decode
    a.side = 'B';
    a.qty = 0;
    std::snprintf(a.orderbook_id, sizeof(a.orderbook_id), "8306");
    std::snprintf(a.group, sizeof(a.group), "DAY");
    a.price = jnx::NO_PRICE;
    unsigned char buf[64];
    size_t n = jnx::encode(a, buf);
    CHECK_EQ(n, static_cast<size_t>(30));
    jnx::ItchMsg out;
    const char* err = NULL;
    CHECK(jnx::decode(buf, n, out, &err));
    CHECK_EQ(out.price, jnx::NO_PRICE);
    CHECK_EQ(out.order_number, static_cast<uint64_t>(0));
    CHECK_EQ(std::string(1, out.type), std::string("A"));
}
